### ISSUE TITLE
can't edit path in godoot V4.2.1

### ISSUE THREAD

**Issue by sonicbigfan** [rsubtil/controller_icons#81] opened 2024-03-13 23:26 UTC
when i try to edit the path in controllericontexture it is not letting me edit it.
![Screenshot from 2024-03-13 16-16-27](https://github.com/rsubtil/controller_icons/assets/59119524/02be8445-fea5-4ca5-a1d1-a7f2bd8f3b1d)

**Comment by rsubtil** [comment] 2024-03-14 09:57
Huum, I've just tried a fresh install of the addon on `v4.2.1-stable`, and cannot reproduce this issue in any way.

Could you open the `res://addons/controller_icons/objects/ControllerIconPathSelectorPopup.tscn` scene and check how it looks like? For some reason the root node seems to have changed to the inner `PanelContainer` child; it should be a `ConfirmationDialog`, like so:
![image](https://github.com/rsubtil/controller_icons/assets/6501975/c4793c00-ed1e-4532-87a9-99f6a1142b6d)

**Comment by sonicbigfan** [comment] 2024-03-14 13:37
it looks like this 
![Screenshot from 2024-03-14 06-36-20](https://github.com/rsubtil/controller_icons/assets/59119524/3e60b9bc-9af8-4322-80ae-247ed1390efc)

**Comment by rsubtil** [comment] 2024-03-14 14:30
Can you try installing the addon on a brand new project to see if the issue still occurs?

**Comment by sonicbigfan** [comment] 2024-03-14 23:20
i installed it in a new project and now i can't even see the controllerIconTexture now 
![Screenshot from 2024-03-14 16-15-34](https://github.com/rsubtil/controller_icons/assets/59119524/88aa5ec4-a736-41e4-8feb-8a90368447e5)
and i turned on the plugin 
![Screenshot from 2024-03-14 16-15-45](https://github.com/rsubtil/controller_icons/assets/59119524/7834bab3-7d27-4f14-9966-3f33e13880ee)

**Comment by sonicbigfan** [comment] 2024-03-15 00:18
nvm i had to reinstalled it to work. thanks for trying to help, it a good plugin to save time

**Comment by rsubtil** [comment] 2024-03-15 10:55
> nvm i had to reinstalled it to work. thanks for trying to help, it a good plugin to save time

Yes, currently the project needs to be reloaded after installing the plugin due to how Godot works.

Does this mean it now works in your original project too?

**Comment by rsubtil** [comment] 2024-03-15 19:30
Thank you, I'll go ahead and close this issue then. Lemme know of any other problems you might find!

**Closed by rsubtil** 2024-03-15 19:30 UTC
