### ISSUE TITLE
Waiting for a mono version

### ISSUE THREAD

**Issue by LutherShaw8888** [rsubtil/controller_icons#47] opened 2023-03-11 03:38 UTC
The current version seems not support Godot mono versions with the error info of "isn't declared in the current scope".

**Comment by rsubtil** [comment] 2023-03-11 15:15
Can you give more details on the exact error, and how you're using the addon? I've never used Godot C#'s version, but I believe it still supports GDScript internally.

**Comment by LutherShaw8888** [comment] 2023-03-13 01:52
After importing this add-on, errors come out like bellow. So I think it's necessary to change all GD scripts to C# scripts:
![error](https://user-images.githubusercontent.com/36783390/224590131-8f2f71ad-615f-4758-b9d6-e444287d5183.jpg)

**Comment by rsubtil** [comment] 2023-03-13 09:50
I've tested with both Godot 3.5.2 and 4.0 C# versions, and that error never occurs. It also doesn't seem specific to being C# or not, it looks like an error with the addon's scripts.

Try removing the addon completely by deleting the `addons/controller_icons` folder from your project, and then install it again from the Asset Lib.

If the error persists, please submit a reproduction project so I can have a better look.

**Comment by LutherShaw8888** [comment] 2023-03-19 02:50
Got it! I have forgotten to enable this add-on in the plugin panel. By the way, will you consider to add a joystick rolling button to control moving not just joystick pressing buttons as they are doing now? Thank you.

**Comment by rsubtil** [comment] 2023-03-19 18:49
I did not create these assets and I don't feel like can make new ones that match the same art style. If these icons get updated by the original creator though, I'll update them here.

If you want to use new or different icons in your project, check [here](https://github.com/rsubtil/controller_icons/blob/master/DOCS.md#addingremoving-controller-icons) for how to do it.

Closing the issue since it was not a bug :+1:

**Closed by rsubtil** 2023-03-19 18:49 UTC
