### ISSUE TITLE
Glyphs for controller events configured for "All devices" are not shown in Godot 4.4

### ISSUE THREAD

**Issue by carllacan** [rsubtil/controller_icons#126] opened 2024-12-30 13:59 UTC
Hi.

The plug-in does not work in Godot 4.4 for controller events marked as "For All Devices". It works if you configure them for a particular device (say, 0). The exact same project does show the glyphs in Godot 4.3.

I've found some bizarre behaviour that explains this: InputEvent objects use -1 to signify "For All Devices" in Godot 4.3, but 4.4 uses -3. Go figure.

I haven't bothered to try and reproduce this in Godot > 4.4, but the fix is simple check for negative device IDs, rather than specifically -1.

**Comment by rsubtil** [comment] 2024-12-31 10:38
Thanks for reporting this! This is a duplicate of https://github.com/rsubtil/controller_icons/issues/116; it seems this was changed sometime between 4.3 and 4.4, and subsequently reverted.

This is fixed with https://github.com/rsubtil/controller_icons/pull/117, but I haven't prepared a release yet. But since 4.4 is getting closer to release, I'll prepare a new version with this fix.

**Closed by rsubtil** 2024-12-31 10:38 UTC
